language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

#services:
#  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

install:
  - pip install -r station/requirements.txt
  - pip install -r server/requirements.txt
  - pip install pytest

before_script:
  - psql -c 'create database satnogs;' -U postgres
  - cp server/.satnogs.ini.travis server/satnogs.ini
  - cd server && python migrate_db.py && cd ..
  - psql -f server/tests/db-data.psql satnogs
  - mkdir -p ~/.config/satnogs-gut

script:
  - cd station && pytest -v && cd ..
  - cd server && PYTHONTEST=. pytest -v

notifications:
  email:
    recipients:
      - spam.travis@klub.com.pl
    on_success: change
    on_failure: always
