language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

#services:
#  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

install:
  - pip install -r automation/requirements.txt
  - pip install -r backend/requirements.txt
  - pip install pytest

before_script:
  - psql -c 'create database satnogs;' -U postgres
  - cp backend/.satnogs.ini.travis backend/satnogs.ini
  - cd backend && python migrate-db.py && cd ..
  - psql -f backend/tests/db-data.psql satnogs
  - mkdir -p ~/.config/satnogs-gut

script:
  - cd automation && pytest -v && cd ..
  - cd backend && PYTHONTEST=. pytest -v

notifications:
  email:
    recipients:
      - spam.travis@klub.com.pl
    on_success: change
    on_failure: always
