language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - pip3 install pytest
  - pip3 install DateTimeRange orbit_predictor
  - pip3 install flask psycopg2 webargs

script:
  - cd automation && pytest -v
  - cd ../backend && PYTHONTEST=. pytest -v

notifications:
  email:
    recipients:
      - spam.travis@klub.com.pl
    on_success: change
    on_failure: always
