location:
  name: Taneczna
  latitude: 54.3833
  longitude: 18.4667
  elevation: 138
satellites:
  - name: NOAA 15
    freq: 137.62e6
  - name: NOAA 18
    freq: 137.9125e6
  - name: NOAA 19
    freq: 137.1e6
aos_at: 0
max_elevation_greater_than: 0


